[__POOL__]
user = __USER__
group = __USER__
listen = /run/php/__POOL__.sock
listen.owner = www-data
listen.group = www-data
listen.mode = 0660

pm = ondemand
pm.max_children = 8
pm.process_idle_timeout = 20s
pm.max_requests = 200

chdir = /home/__USER__
catch_workers_output = yes
security.limit_extensions = .php

php_admin_value[memory_limit] = __MEMORY__
php_admin_value[open_basedir] = /home/__USER__:/tmp
php_admin_value[upload_tmp_dir] = /home/__USER__/tmp
php_admin_value[session.save_path] = /home/__USER__/tmp
php_admin_value[disable_functions] = exec,passthru,shell_exec,system,proc_open,popen,pcntl_exec,dl
php_admin_flag[allow_url_fopen] = on
