/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PanelRouteImport } from './routes/_panel'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as PanelIndexRouteImport } from './routes/_panel.index'
import { Route as PanelAppsRouteImport } from './routes/_panel.apps'
import { Route as PanelDnsRouteImport } from './routes/_panel.dns'
import { Route as PanelFirewallRouteImport } from './routes/_panel.firewall'
import { Route as PanelInstallRouteImport } from './routes/_panel.install'
import { Route as PanelMailRouteImport } from './routes/_panel.mail'
import { Route as PanelModulesRouteImport } from './routes/_panel.modules'
import { Route as PanelSettingsRouteImport } from './routes/_panel.settings'
import { Route as PanelSitesRouteImport } from './routes/_panel.sites'
import { Route as PanelSitesIndexRouteImport } from './routes/_panel.sites.index'
import { Route as PanelSitesIdRouteImport } from './routes/_panel.sites.$id'

const PanelRoute = PanelRouteImport.update({
  id: '/_panel',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelIndexRoute = PanelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PanelRoute,
} as any)
const PanelAppsRoute = PanelAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => PanelRoute,
} as any)
const PanelDnsRoute = PanelDnsRouteImport.update({
  id: '/dns',
  path: '/dns',
  getParentRoute: () => PanelRoute,
} as any)
const PanelFirewallRoute = PanelFirewallRouteImport.update({
  id: '/firewall',
  path: '/firewall',
  getParentRoute: () => PanelRoute,
} as any)
const PanelInstallRoute = PanelInstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => PanelRoute,
} as any)
const PanelMailRoute = PanelMailRouteImport.update({
  id: '/mail',
  path: '/mail',
  getParentRoute: () => PanelRoute,
} as any)
const PanelModulesRoute = PanelModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => PanelRoute,
} as any)
const PanelSettingsRoute = PanelSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PanelRoute,
} as any)
const PanelSitesRoute = PanelSitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => PanelRoute,
} as any)
const PanelSitesIndexRoute = PanelSitesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PanelSitesRoute,
} as any)
const PanelSitesIdRoute = PanelSitesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PanelSitesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PanelIndexRoute
  '/setup': typeof SetupRoute
  '/apps': typeof PanelAppsRoute
  '/dns': typeof PanelDnsRoute
  '/firewall': typeof PanelFirewallRoute
  '/install': typeof PanelInstallRoute
  '/mail': typeof PanelMailRoute
  '/modules': typeof PanelModulesRoute
  '/settings': typeof PanelSettingsRoute
  '/sites': typeof PanelSitesRouteWithChildren
  '/sites/$id': typeof PanelSitesIdRoute
  '/sites/': typeof PanelSitesIndexRoute
}
export interface FileRoutesByTo {
  '/setup': typeof SetupRoute
  '/apps': typeof PanelAppsRoute
  '/dns': typeof PanelDnsRoute
  '/firewall': typeof PanelFirewallRoute
  '/install': typeof PanelInstallRoute
  '/mail': typeof PanelMailRoute
  '/modules': typeof PanelModulesRoute
  '/settings': typeof PanelSettingsRoute
  '/': typeof PanelIndexRoute
  '/sites/$id': typeof PanelSitesIdRoute
  '/sites': typeof PanelSitesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_panel': typeof PanelRouteWithChildren
  '/setup': typeof SetupRoute
  '/_panel/apps': typeof PanelAppsRoute
  '/_panel/dns': typeof PanelDnsRoute
  '/_panel/firewall': typeof PanelFirewallRoute
  '/_panel/install': typeof PanelInstallRoute
  '/_panel/mail': typeof PanelMailRoute
  '/_panel/modules': typeof PanelModulesRoute
  '/_panel/settings': typeof PanelSettingsRoute
  '/_panel/sites': typeof PanelSitesRouteWithChildren
  '/_panel/': typeof PanelIndexRoute
  '/_panel/sites/$id': typeof PanelSitesIdRoute
  '/_panel/sites/': typeof PanelSitesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/setup'
    | '/apps'
    | '/dns'
    | '/firewall'
    | '/install'
    | '/mail'
    | '/modules'
    | '/settings'
    | '/sites'
    | '/sites/$id'
    | '/sites/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/setup'
    | '/apps'
    | '/dns'
    | '/firewall'
    | '/install'
    | '/mail'
    | '/modules'
    | '/settings'
    | '/'
    | '/sites/$id'
    | '/sites'
  id:
    | '__root__'
    | '/_panel'
    | '/setup'
    | '/_panel/apps'
    | '/_panel/dns'
    | '/_panel/firewall'
    | '/_panel/install'
    | '/_panel/mail'
    | '/_panel/modules'
    | '/_panel/settings'
    | '/_panel/sites'
    | '/_panel/'
    | '/_panel/sites/$id'
    | '/_panel/sites/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PanelRoute: typeof PanelRouteWithChildren
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_panel': {
      id: '/_panel'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_panel/': {
      id: '/_panel/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PanelIndexRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/apps': {
      id: '/_panel/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof PanelAppsRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/dns': {
      id: '/_panel/dns'
      path: '/dns'
      fullPath: '/dns'
      preLoaderRoute: typeof PanelDnsRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/firewall': {
      id: '/_panel/firewall'
      path: '/firewall'
      fullPath: '/firewall'
      preLoaderRoute: typeof PanelFirewallRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/install': {
      id: '/_panel/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof PanelInstallRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/mail': {
      id: '/_panel/mail'
      path: '/mail'
      fullPath: '/mail'
      preLoaderRoute: typeof PanelMailRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/modules': {
      id: '/_panel/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof PanelModulesRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/settings': {
      id: '/_panel/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof PanelSettingsRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/sites': {
      id: '/_panel/sites'
      path: '/sites'
      fullPath: '/sites'
      preLoaderRoute: typeof PanelSitesRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/sites/': {
      id: '/_panel/sites/'
      path: '/'
      fullPath: '/sites/'
      preLoaderRoute: typeof PanelSitesIndexRouteImport
      parentRoute: typeof PanelSitesRoute
    }
    '/_panel/sites/$id': {
      id: '/_panel/sites/$id'
      path: '/$id'
      fullPath: '/sites/$id'
      preLoaderRoute: typeof PanelSitesIdRouteImport
      parentRoute: typeof PanelSitesRoute
    }
  }
}

interface PanelSitesRouteChildren {
  PanelSitesIdRoute: typeof PanelSitesIdRoute
  PanelSitesIndexRoute: typeof PanelSitesIndexRoute
}

const PanelSitesRouteChildren: PanelSitesRouteChildren = {
  PanelSitesIdRoute: PanelSitesIdRoute,
  PanelSitesIndexRoute: PanelSitesIndexRoute,
}

const PanelSitesRouteWithChildren = PanelSitesRoute._addFileChildren(
  PanelSitesRouteChildren,
)

interface PanelRouteChildren {
  PanelAppsRoute: typeof PanelAppsRoute
  PanelDnsRoute: typeof PanelDnsRoute
  PanelFirewallRoute: typeof PanelFirewallRoute
  PanelInstallRoute: typeof PanelInstallRoute
  PanelMailRoute: typeof PanelMailRoute
  PanelModulesRoute: typeof PanelModulesRoute
  PanelSettingsRoute: typeof PanelSettingsRoute
  PanelSitesRoute: typeof PanelSitesRouteWithChildren
  PanelIndexRoute: typeof PanelIndexRoute
}

const PanelRouteChildren: PanelRouteChildren = {
  PanelAppsRoute: PanelAppsRoute,
  PanelDnsRoute: PanelDnsRoute,
  PanelFirewallRoute: PanelFirewallRoute,
  PanelInstallRoute: PanelInstallRoute,
  PanelMailRoute: PanelMailRoute,
  PanelModulesRoute: PanelModulesRoute,
  PanelSettingsRoute: PanelSettingsRoute,
  PanelSitesRoute: PanelSitesRouteWithChildren,
  PanelIndexRoute: PanelIndexRoute,
}

const PanelRouteWithChildren = PanelRoute._addFileChildren(PanelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PanelRoute: PanelRouteWithChildren,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
