/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PanelRouteImport } from './routes/_panel'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as WebmailRouteImport } from './routes/webmail'
import { Route as PanelIndexRouteImport } from './routes/_panel.index'
import { Route as PanelAppsRouteImport } from './routes/_panel.apps'
import { Route as PanelBackupsRouteImport } from './routes/_panel.backups'
import { Route as PanelCronRouteImport } from './routes/_panel.cron'
import { Route as PanelDnsRouteImport } from './routes/_panel.dns'
import { Route as PanelFilesRouteImport } from './routes/_panel.files'
import { Route as PanelFirewallRouteImport } from './routes/_panel.firewall'
import { Route as PanelInstallRouteImport } from './routes/_panel.install'
import { Route as PanelIpsRouteImport } from './routes/_panel.ips'
import { Route as PanelMailRouteImport } from './routes/_panel.mail'
import { Route as PanelModulesRouteImport } from './routes/_panel.modules'
import { Route as PanelRedisRouteImport } from './routes/_panel.redis'
import { Route as PanelSettingsRouteImport } from './routes/_panel.settings'
import { Route as PanelSitesRouteImport } from './routes/_panel.sites'
import { Route as WebmailIndexRouteImport } from './routes/webmail.index'
import { Route as WebmailInboxRouteImport } from './routes/webmail.inbox'
import { Route as PanelSitesIndexRouteImport } from './routes/_panel.sites.index'
import { Route as PanelSitesIdRouteImport } from './routes/_panel.sites.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const PanelRoute = PanelRouteImport.update({
  id: '/_panel',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const WebmailRoute = WebmailRouteImport.update({
  id: '/webmail',
  path: '/webmail',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelIndexRoute = PanelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PanelRoute,
} as any)
const PanelAppsRoute = PanelAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => PanelRoute,
} as any)
const PanelBackupsRoute = PanelBackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => PanelRoute,
} as any)
const PanelCronRoute = PanelCronRouteImport.update({
  id: '/cron',
  path: '/cron',
  getParentRoute: () => PanelRoute,
} as any)
const PanelDnsRoute = PanelDnsRouteImport.update({
  id: '/dns',
  path: '/dns',
  getParentRoute: () => PanelRoute,
} as any)
const PanelFilesRoute = PanelFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => PanelRoute,
} as any)
const PanelFirewallRoute = PanelFirewallRouteImport.update({
  id: '/firewall',
  path: '/firewall',
  getParentRoute: () => PanelRoute,
} as any)
const PanelInstallRoute = PanelInstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => PanelRoute,
} as any)
const PanelIpsRoute = PanelIpsRouteImport.update({
  id: '/ips',
  path: '/ips',
  getParentRoute: () => PanelRoute,
} as any)
const PanelMailRoute = PanelMailRouteImport.update({
  id: '/mail',
  path: '/mail',
  getParentRoute: () => PanelRoute,
} as any)
const PanelModulesRoute = PanelModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => PanelRoute,
} as any)
const PanelRedisRoute = PanelRedisRouteImport.update({
  id: '/redis',
  path: '/redis',
  getParentRoute: () => PanelRoute,
} as any)
const PanelSettingsRoute = PanelSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PanelRoute,
} as any)
const PanelSitesRoute = PanelSitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => PanelRoute,
} as any)
const WebmailIndexRoute = WebmailIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WebmailRoute,
} as any)
const WebmailInboxRoute = WebmailInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => WebmailRoute,
} as any)
const PanelSitesIndexRoute = PanelSitesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PanelSitesRoute,
} as any)
const PanelSitesIdRoute = PanelSitesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PanelSitesRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PanelIndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/webmail': typeof WebmailRouteWithChildren
  '/apps': typeof PanelAppsRoute
  '/backups': typeof PanelBackupsRoute
  '/cron': typeof PanelCronRoute
  '/dns': typeof PanelDnsRoute
  '/files': typeof PanelFilesRoute
  '/firewall': typeof PanelFirewallRoute
  '/install': typeof PanelInstallRoute
  '/ips': typeof PanelIpsRoute
  '/mail': typeof PanelMailRoute
  '/modules': typeof PanelModulesRoute
  '/redis': typeof PanelRedisRoute
  '/settings': typeof PanelSettingsRoute
  '/sites': typeof PanelSitesRouteWithChildren
  '/webmail/inbox': typeof WebmailInboxRoute
  '/webmail/': typeof WebmailIndexRoute
  '/sites/$id': typeof PanelSitesIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/sites/': typeof PanelSitesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/apps': typeof PanelAppsRoute
  '/backups': typeof PanelBackupsRoute
  '/cron': typeof PanelCronRoute
  '/dns': typeof PanelDnsRoute
  '/files': typeof PanelFilesRoute
  '/firewall': typeof PanelFirewallRoute
  '/install': typeof PanelInstallRoute
  '/ips': typeof PanelIpsRoute
  '/mail': typeof PanelMailRoute
  '/modules': typeof PanelModulesRoute
  '/redis': typeof PanelRedisRoute
  '/settings': typeof PanelSettingsRoute
  '/webmail/inbox': typeof WebmailInboxRoute
  '/': typeof PanelIndexRoute
  '/webmail': typeof WebmailIndexRoute
  '/sites/$id': typeof PanelSitesIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/sites': typeof PanelSitesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_panel': typeof PanelRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/webmail': typeof WebmailRouteWithChildren
  '/_panel/apps': typeof PanelAppsRoute
  '/_panel/backups': typeof PanelBackupsRoute
  '/_panel/cron': typeof PanelCronRoute
  '/_panel/dns': typeof PanelDnsRoute
  '/_panel/files': typeof PanelFilesRoute
  '/_panel/firewall': typeof PanelFirewallRoute
  '/_panel/install': typeof PanelInstallRoute
  '/_panel/ips': typeof PanelIpsRoute
  '/_panel/mail': typeof PanelMailRoute
  '/_panel/modules': typeof PanelModulesRoute
  '/_panel/redis': typeof PanelRedisRoute
  '/_panel/settings': typeof PanelSettingsRoute
  '/_panel/sites': typeof PanelSitesRouteWithChildren
  '/webmail/inbox': typeof WebmailInboxRoute
  '/_panel/': typeof PanelIndexRoute
  '/webmail/': typeof WebmailIndexRoute
  '/_panel/sites/$id': typeof PanelSitesIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_panel/sites/': typeof PanelSitesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/setup'
    | '/webmail'
    | '/apps'
    | '/backups'
    | '/cron'
    | '/dns'
    | '/files'
    | '/firewall'
    | '/install'
    | '/ips'
    | '/mail'
    | '/modules'
    | '/redis'
    | '/settings'
    | '/sites'
    | '/webmail/inbox'
    | '/webmail/'
    | '/sites/$id'
    | '/api/auth/$'
    | '/sites/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/setup'
    | '/apps'
    | '/backups'
    | '/cron'
    | '/dns'
    | '/files'
    | '/firewall'
    | '/install'
    | '/ips'
    | '/mail'
    | '/modules'
    | '/redis'
    | '/settings'
    | '/webmail/inbox'
    | '/'
    | '/webmail'
    | '/sites/$id'
    | '/api/auth/$'
    | '/sites'
  id:
    | '__root__'
    | '/_panel'
    | '/login'
    | '/setup'
    | '/webmail'
    | '/_panel/apps'
    | '/_panel/backups'
    | '/_panel/cron'
    | '/_panel/dns'
    | '/_panel/files'
    | '/_panel/firewall'
    | '/_panel/install'
    | '/_panel/ips'
    | '/_panel/mail'
    | '/_panel/modules'
    | '/_panel/redis'
    | '/_panel/settings'
    | '/_panel/sites'
    | '/webmail/inbox'
    | '/_panel/'
    | '/webmail/'
    | '/_panel/sites/$id'
    | '/api/auth/$'
    | '/_panel/sites/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PanelRoute: typeof PanelRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
  WebmailRoute: typeof WebmailRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_panel': {
      id: '/_panel'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webmail': {
      id: '/webmail'
      path: '/webmail'
      fullPath: '/webmail'
      preLoaderRoute: typeof WebmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_panel/': {
      id: '/_panel/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PanelIndexRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/apps': {
      id: '/_panel/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof PanelAppsRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/backups': {
      id: '/_panel/backups'
      path: '/backups'
      fullPath: '/backups'
      preLoaderRoute: typeof PanelBackupsRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/cron': {
      id: '/_panel/cron'
      path: '/cron'
      fullPath: '/cron'
      preLoaderRoute: typeof PanelCronRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/dns': {
      id: '/_panel/dns'
      path: '/dns'
      fullPath: '/dns'
      preLoaderRoute: typeof PanelDnsRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/files': {
      id: '/_panel/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof PanelFilesRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/firewall': {
      id: '/_panel/firewall'
      path: '/firewall'
      fullPath: '/firewall'
      preLoaderRoute: typeof PanelFirewallRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/install': {
      id: '/_panel/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof PanelInstallRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/ips': {
      id: '/_panel/ips'
      path: '/ips'
      fullPath: '/ips'
      preLoaderRoute: typeof PanelIpsRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/mail': {
      id: '/_panel/mail'
      path: '/mail'
      fullPath: '/mail'
      preLoaderRoute: typeof PanelMailRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/modules': {
      id: '/_panel/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof PanelModulesRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/redis': {
      id: '/_panel/redis'
      path: '/redis'
      fullPath: '/redis'
      preLoaderRoute: typeof PanelRedisRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/settings': {
      id: '/_panel/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof PanelSettingsRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/sites': {
      id: '/_panel/sites'
      path: '/sites'
      fullPath: '/sites'
      preLoaderRoute: typeof PanelSitesRouteImport
      parentRoute: typeof PanelRoute
    }
    '/webmail/': {
      id: '/webmail/'
      path: '/'
      fullPath: '/webmail/'
      preLoaderRoute: typeof WebmailIndexRouteImport
      parentRoute: typeof WebmailRoute
    }
    '/webmail/inbox': {
      id: '/webmail/inbox'
      path: '/inbox'
      fullPath: '/webmail/inbox'
      preLoaderRoute: typeof WebmailInboxRouteImport
      parentRoute: typeof WebmailRoute
    }
    '/_panel/sites/': {
      id: '/_panel/sites/'
      path: '/'
      fullPath: '/sites/'
      preLoaderRoute: typeof PanelSitesIndexRouteImport
      parentRoute: typeof PanelSitesRoute
    }
    '/_panel/sites/$id': {
      id: '/_panel/sites/$id'
      path: '/$id'
      fullPath: '/sites/$id'
      preLoaderRoute: typeof PanelSitesIdRouteImport
      parentRoute: typeof PanelSitesRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PanelSitesRouteChildren {
  PanelSitesIdRoute: typeof PanelSitesIdRoute
  PanelSitesIndexRoute: typeof PanelSitesIndexRoute
}

const PanelSitesRouteChildren: PanelSitesRouteChildren = {
  PanelSitesIdRoute: PanelSitesIdRoute,
  PanelSitesIndexRoute: PanelSitesIndexRoute,
}

const PanelSitesRouteWithChildren = PanelSitesRoute._addFileChildren(
  PanelSitesRouteChildren,
)

interface PanelRouteChildren {
  PanelAppsRoute: typeof PanelAppsRoute
  PanelBackupsRoute: typeof PanelBackupsRoute
  PanelCronRoute: typeof PanelCronRoute
  PanelDnsRoute: typeof PanelDnsRoute
  PanelFilesRoute: typeof PanelFilesRoute
  PanelFirewallRoute: typeof PanelFirewallRoute
  PanelInstallRoute: typeof PanelInstallRoute
  PanelIpsRoute: typeof PanelIpsRoute
  PanelMailRoute: typeof PanelMailRoute
  PanelModulesRoute: typeof PanelModulesRoute
  PanelRedisRoute: typeof PanelRedisRoute
  PanelSettingsRoute: typeof PanelSettingsRoute
  PanelSitesRoute: typeof PanelSitesRouteWithChildren
  PanelIndexRoute: typeof PanelIndexRoute
}

const PanelRouteChildren: PanelRouteChildren = {
  PanelAppsRoute: PanelAppsRoute,
  PanelBackupsRoute: PanelBackupsRoute,
  PanelCronRoute: PanelCronRoute,
  PanelDnsRoute: PanelDnsRoute,
  PanelFilesRoute: PanelFilesRoute,
  PanelFirewallRoute: PanelFirewallRoute,
  PanelInstallRoute: PanelInstallRoute,
  PanelIpsRoute: PanelIpsRoute,
  PanelMailRoute: PanelMailRoute,
  PanelModulesRoute: PanelModulesRoute,
  PanelRedisRoute: PanelRedisRoute,
  PanelSettingsRoute: PanelSettingsRoute,
  PanelSitesRoute: PanelSitesRouteWithChildren,
  PanelIndexRoute: PanelIndexRoute,
}

const PanelRouteWithChildren = PanelRoute._addFileChildren(PanelRouteChildren)

interface WebmailRouteChildren {
  WebmailInboxRoute: typeof WebmailInboxRoute
  WebmailIndexRoute: typeof WebmailIndexRoute
}

const WebmailRouteChildren: WebmailRouteChildren = {
  WebmailInboxRoute: WebmailInboxRoute,
  WebmailIndexRoute: WebmailIndexRoute,
}

const WebmailRouteWithChildren =
  WebmailRoute._addFileChildren(WebmailRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PanelRoute: PanelRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
  WebmailRoute: WebmailRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
